<script lang="ts" setup>
import { computed, onMounted, reactive, watch } from 'vue';
import { useRoute } from 'vue-router';
import { Content } from '@/shared/content';
import { useCategoryProductsStore } from '@/app/stores/categoryProducts';
import { useCategoriesStore } from '@/app/stores/categories';
import { Products } from '@/widgets/products';
import token from '@/token';

const route = useRoute();

const storeCategoryProducts = useCategoryProductsStore();
const storeCategories = useCategoriesStore();

const state = reactive({
    category: null as null | { id: number; name: string } | undefined,
    title: ''
});

watch(
  () => state.category,
  (newCategory) => {
    if (newCategory) {
      state.title = newCategory.name; 
    } else {
      state.title = 'Category not found';
    }
  }
);

onMounted(async () => {
    storeCategoryProducts.clearCategoryProducts();
    await storeCategories.loadCategories(token);
    state.category = storeCategories.categories.find(
        (el) => el.autogeneratedSlug === route.params.category_name
    );
    if (state.category) {
        storeCategoryProducts.loadCategoryProducts(
            token,
            state.category.id
        );
    } else {
        console.error('Category not found');
    }
});

const productsData = computed(() => ({
    title: state.title,
    items: storeCategoryProducts.products,
}));


</script>

<template>
    <Content>
        <Products :data="productsData" />
    </Content>
</template>