<script setup lang="ts">
import { Content } from '@/shared/content';
import { Typography } from '@/shared/typograghy';
import { Button } from '@/shared/button';
import { useProductDetailsStore } from '@/app/stores/singleProduct';
import { useAllProductsStore } from '@/app/stores/allProducts';
import { type Product } from '@/entities/product/model/types';
import { useRoute } from 'vue-router';
import { computed, onMounted, reactive, watch } from 'vue';
import { useShoppingCartStore } from '@/app/stores/shoppingCart';
import token from '@/token';

const route = useRoute();

const storeProductDetails = useProductDetailsStore();
const storeAllProducts = useAllProductsStore();
const storeShoppingCart = useShoppingCartStore();


const state = reactive({
    product: null as null | Product | undefined,
    id: null as null | number | string
});

watch(
  () => state.product,
  (newProduct) => {
    if (newProduct) {
      state.id = newProduct.id; 
    } else {
      state.id = 'Product ID not found';
    }
  }
);

onMounted(async () => {
  storeProductDetails.clearProductDetails();
  await storeAllProducts.loadProducts(token);
  state.product = storeAllProducts.products.find(el => el.autogeneratedSlug === route.params.product_name);
  if (state.product) {
    storeProductDetails.loadProductDetails(
      token,
      state.product.id
    );
  } else {
    console.error('Product not found');
  }
});

const addToCart = () => {
  if (state.product) {
    storeShoppingCart.addProduct(state.product);
  }
};

const removeFromCart = () => {
  if (state.product) {
    storeShoppingCart.removeProduct(state.product.id)
  }
};

const productInTheCart = computed(() =>storeShoppingCart.cartProducts.find(el => el.id === state.product?.id));

</script>

<template>
  <Content>
    <section class="product-details">
      <img :src="state.product?.originalImageUrl" :alt="state.product?.name" class="product-details__image">
      <div class="product-details__data">
        <Typography 
          tagName="h3" 
          v-if="state.product" 
        >
          {{ state.product.name }}
        </Typography>
        <div v-if="state.product" v-html="state.product.description" class="product-details__description"></div>  
        <Button 
          color="dark" 
          class="product-details__button" 
          v-if="state.product && !productInTheCart"
          @click="addToCart"
        >
          Add to cart
        </Button>

        <Button 
          color="secondary" 
          class="product-card__button_added"
          v-if="state.product && productInTheCart"
          @click="removeFromCart"
        >
          Already in the cart
        </Button>
      </div>  
    </section>
  </Content>
</template>

<style scoped>
.product-details {
  display: flex;
  gap: 60px;
}

.product-details__image {
  max-width: 700px;
  object-fit: contain;
}

.product-details__data {
  display: flex;
  flex-direction: column;
  gap: 25px;
}

.product-details__description {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.product-details__button {
  cursor: pointer;
}

.product-details__button:hover {
  background-color: rgba(25, 25, 25, 0.8);
}

@media screen and (max-width: 768px){
  .product-details {
    flex-direction: column;
  }

  .product-details__image {
    max-width: 480px;
  }
}
</style>
