<script lang="ts" setup>
import { Typography } from '@/shared/typograghy';
import { type Category } from '../model/types';
import { RouterLink } from 'vue-router';

const { data } = defineProps<{ data: Category }>();
const { autogeneratedSlug, name = 'NA' } = data;
</script>

<template>
    <RouterLink :to="`/products/${autogeneratedSlug}`" class="item">
        <article>
            <Typography tag-name="p" fontSize="l">{{ name }}</Typography>
        </article>
    </RouterLink>
</template>

<style scoped>
.item {
    color: var(--main-on-secondary);
    text-decoration: none;
    background-color: var(--grayscale-light);
    padding: 30px;
    border-radius: 3px;
    display: flex;
    justify-content: center;
    transition: transform 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease;
}

.item:hover {
    background-color: var(--grayscale-hard);  
    transform: scale(1.05);                    
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1); 
}

.item:hover p {
    color: var(--primary-color);
}
</style>