export interface Product {
    id: number,
    originalImageUrl: string;
    thumbnailUrl: string;
    name: string;
    price: number;
    defaultDisplayedPriceFormatted: string;
    autogeneratedSlug: string;
    description: string;
}