<script lang="ts" setup>
import { type Product } from '../model/types';
import { Typography } from '@/shared/typograghy';
import { RouterLink } from 'vue-router';
import { Button } from '@/shared/button';
import { useShoppingCartStore } from '@/app/stores/shoppingCart';
import { computed } from 'vue';

const storeShoppingCart = useShoppingCartStore();

const { data } = defineProps<{ data: Product }>();
const { id, originalImageUrl, autogeneratedSlug, defaultDisplayedPriceFormatted, name } = data;

const addToCart = () => storeShoppingCart.addProduct(data);
const removeFromCart = () => storeShoppingCart.removeProduct(id);

const productInTheCart = computed(() => storeShoppingCart.cartProducts.find(el => el.id === id));

</script>

<template>
    <article class="product-card">
        <RouterLink :to="`/product/${autogeneratedSlug}`" class="product-card__item">
            <div 
                class="product-card__image" 
                :style="{ backgroundImage: `url(${originalImageUrl})` }"
            />
            <Typography tagName="p" fontSize="m">{{ name }}</Typography>
            <Typography tagName="p" fontSize="l" bold>{{ defaultDisplayedPriceFormatted }}</Typography>
        </RouterLink>
        <Button 
            color="dark" 
            class="product-card__button" 
            v-if="!productInTheCart"
            @click="addToCart"
        >
            Add to cart
        </Button>
        <Button 
            color="secondary" 
            class="product-card__button_added"
            v-else 
            @click="removeFromCart"
        >
            Already in the cart
        </Button>
    </article>
</template>

<style scoped>
.product-card {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 15px;
    text-decoration: none;
    background: #fff;
    border-radius: 8px;
    overflow: hidden; 
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    padding-bottom: 20px; 
}

.product-card__item {
    color: var(--main-on-surface);
    text-decoration: none;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 15px;
}

.product-card:hover {
    transform: scale(1.05); 
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1); 
}

.product-card__image {
    width: 100%;
    height: 500px;
    background-size: cover;
    background-position: center;
    transition: transform 0.3s ease; 
}

.product-card:hover .product-card__image {
    transform: scale(1.03); 
}

.product-card__item > p {
    text-align: center;
    padding: 0 20px;
}

.product-card__button,
.product-card__button_added {
    visibility: hidden;
    transition: background-color 0.3s ease;
    margin: 0 20px;
}

.product-card:hover .product-card__button, 
.product-card:hover .product-card__button_added {
    visibility: visible;
}

.product-card__button:hover {
    background-color: var(--main-secondary);
}

.product-card__button_added:hover {
    background-color: var(--main-dark);
}

</style>